### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by Eevangelion** [miegir/AI2Tools#1]
При попытке установки перевода возникает следующая ошибка на 411 шаге из 438 (unpacking bundle etc_assets_all...):

![image](https://github.com/miegir/AI2Tools/assets/100342935/0fae5729-4122-4057-90dc-62d12b308fa4)

**Comment by miegir** [comment]
Похоже, что вам не хватает памяти, т.к. файлы ассетов в игре запакованы, и библиотека AssetTools.NET по умолчанию распаковывает их в памяти. Теоретически можно распаковать в файловую систему, чтобы меньше расходовать память, но для этого требуются дополнительные манипуляции.

Я проверил, у меня при накатывании перевода приложение расходует около 6 ГБ памяти.

**Comment by miegir** [comment]
Забавно, что, разбираясь с etc_assets_all, я обнаружил ошибку при упаковке текстовых файлов перевода, что приводило к тому, что перевод в etc_assets_all не применялся вообще. Переводятся там три текстовых файла - тексты песен для бонусного меню. Я поправлю эту проблему в следующем релизе.

**Comment by miegir** [comment]
Чтобы сократить расход памяти при переводе, на данный момент можно распаковать bundle-файл вручную. Это можно сделать с помощью утилиты AssetsBundleExtractor (UABE), которую можно скачать [здесь](https://community.7daystodie.com/topic/1871-uabe-asset-bundle-extractor/). Можно использовать релиз 3.0 beta 1 (не важно, 32 bit или 64 bit). Когда программа будет скачана и запущена, в ней надо выбрать в меню File/Open, перейти в подраздел `AI_TheSomniumFiles2_Data\StreamingAssets\aa\StandaloneWindows64` раздела с игрой и открыть файл `etc_assets_all_30e8dd0b199420567e04a67ad460be97.bundle`. После открытия файла UABE спросит, куда распаковать файл. Можно выбрать ту же папку. Он создаст в ней файл `etc_assets_all_30e8dd0b199420567e04a67ad460be97.bundle-unpacked`. После этого UABE можно закрыть.

После распаковки смените расширение файла `.bundle` на `.bundle-packed` (это будет бэкап, но не давайте ему расширение `.bak`, т.к. это расширение использует программа перевода), а `.bundle-unpacked` смените на `.bundle`. После этих манипуляций можно запускать переводчик, он не будет распаковывать и упаковывать этот файл, в результате чего объем необходимой оперативной памяти сократится. Игра сможет работать и с распакованным файлом.

Однако, в текущих релизах (1 и 2) есть проблема, не позволяющая накатить перевод на распакованный таким образом файл. Это я тоже поправлю в следующем релизе. Следующий релиз по всей видимости сделаю в ближайший день.

Что же касается усовершенствования программы перевода в плане распаковки в файлы, а не в память - это вряд ли будет быстро.

**Comment by Eevangelion** [comment]
> Похоже, что вам не хватает памяти, т.к. файлы ассетов в игре запакованы, и библиотека AssetTools.NET по умолчанию распаковывает их в памяти. Теоретически можно распаковать в файловую систему, чтобы меньше расходовать память, но для этого требуются дополнительные манипуляции.
> 
> Я проверил, у меня при накатывании перевода приложение расходует около 6 ГБ памяти.

Странно. Оперативной памяти более чем достаточно, но проблема всё равно остаётся. Проделал предложенные действия. Проблему с etc_assets это решило, но далее с fonts_assets такая же беда. С ним такой способ не сработает, т.к. начинает ругаться на то, что файлик занят другим процессом. 

Думаю, самое разумное будет подождать нового релиза. Спасибо за отклик!

**Comment by miegir** [comment]
Загрузил релиз [v2023.08.18](https://github.com/miegir/AI2Tools/releases/tag/v2023.08.18). Проблема с тем, что файл занят другим процессом (им же самим), в нём должна быть исправлена.

К сожалению, вам, возможно, придется некоторые бандлы распаковать вручную. Понимаю, что это неудобно, и не знаю, почему так происходит (у меня не воспроизводится). Но надеюсь, что это вам поможет. Если поможет, то подумаю над автоматической распаковкой в файлы, но, как уже сказал, не факт, что сделаю это быстро.

**Comment by Eevangelion** [comment]
Распаковывал вручную все бандлы последовательно, пока не дошло до video-mv_grandfinale_en_assets_all. С ним работать UABE отказывается (просто игнорирует его).

![image](https://github.com/miegir/AI2Tools/assets/100342935/c62701e5-97f7-4a43-8ec7-c6edd1c42f8d)


Вообще, проблема, видимо, в WINE, т.к. сижу не с винды. Там некоторые проблемы с выделением оперативной памяти. Перепробовал все варианты возможного её увеличения, но всё без толку. Возможно, UABE сломался тоже по этой причине. Так что с Вашей стороны всё, видимо, под контролем.

**Comment by Eevangelion** [comment]
Проблема решилась! Для тех людей, кто планировал поиграть в эту игру на Linux и столкнулся с такой же проблемой решением будет следующее: 
1) Установить себе Lutris
2) Установить lutris-GE-Proton8-8-x86_64 (другие версии, вероятно, тоже сработают)
3) Добавить в Lutris AI2Tools.UI.exe файл с указанием в Runner options версии Wine из пункта 2
4) Запустить через Lutris добавленный скрипт
5) Установка должна успешно завершиться
