### ISSUE TITLE
Вопрос о переводе

### ISSUE THREAD

**Issue by derelictsoul** [miegir/AI2Tools#2]
Доброе утро, не знаю, куда лучше будет написать, поэтому сюда.

У меня вопрос насчет перевода: в базе vndb на него поставили плашку машинного из-за файла
https://github.com/miegir/AI2Tools/blob/master/AI2Tools.Translations/ru/Text/en/a010_Ry_DreamR_StudioDV.txt , т.к. по их правилам, отредактированный машинный перевод все равно считается машинным. Но я слышал, что перевод ручной, да и по фразам видно, что читается он так же, как и любой другой перевод. Можете пояснить подробнее?

Заранее спасибо за ответ.

**Comment by miegir** [comment]
Добрый день. На самом деле во всех файлах из этой папки так. Да, технология у меня такая - я извлекаю английский текст в поле "src", потом прогоняю его через яндекс-переводчик (этой программы в данном репозитории нет, да и официально для этого надо было бы использовать платную службу яндекса), в результате в поле "yax" подставляется переведенный яндекс-переводчиком текст, а в "trx" подставляется тот же текст со специальным маркером. После чего я вручную редактирую "trx" и убираю маркер. Далее инсталлятор заменяет в игре текст "src" на "trx", значение поля "yax" инсталлятором не используется и находится здесь исключительно для информации. В этом репозитории маркера сейчас нигде не увидеть, т.к. весь перевод уже обработан мной.

По моему мнению яндекс-переводчик в некоторых случаях переводит достаточно хорошо. Там, где я считаю, что можно перевести лучше, я изменяю перевод, соответственно в исходниках можно видеть где я это сделал. Изредка перевод яндекс-переводчика - это повод посмеяться. Но в любом случае такая технология сильно ускоряет перевод - вручную писать его в эти файлы было бы для меня дольше, а мне не хочется тратить на это настолько много времени. Причем всё равно я бы в непонятных ситуациях вручную подставлял бы его в яндекс-переводчик и смотрел на результат.

Получается, что процесс перевода текста действительно заключается в редактировании машинного перевода. При этом я редактирую его так, как считаю нужным для того, чтобы он соответствовал в первую очередь моему пониманию оригинального английского текста (который в данном случае является переводом с японского). Если машинный перевод его не передает, я могу полностью его изменить. Если и я бы не сказал лучше - оставляю как есть, это, как и сказано выше, сильно экономит мое время. В процессе редактирования я запускаю игру и смотрю, как он в ней выглядит, и могу что-то переформулировать, чтобы текст влезал в поля, иногда вставляю инструкции для изменения размера шрифта. Я уделяю много внимания орфографии (у меня настроена проверка орфографии для полей "trx", см. https://github.com/miegir/AI2Tools/blob/master/AI2Tools.Translations/ru/ru.vsspell). Я определяю, кто из персонажей к кому обращается на "ты", кто к кому на "вы". Я слежу за тем, чтобы пол персонажей был правильным. Я слежу за тем, чтобы все имена и термины были едиными во всей игре. Я проверяю и корректирую отсылки к каким-то реальным вещам. Я в некоторых местах вставляю примечания переводчика (см. https://github.com/search?q=repo%3Amiegir%2FAI2Tools%20%D0%BF%D1%80%D0%B8%D0%BC.&type=code). Я не смог изменить игровую клавиатуру, используемую для ввода ответов на загадки на русскую, поэтому пришлось оставить там везде оригинальные английские ответы, но я слежу за тем, чтобы эти ответы были упомянуты в тексте игры именно на английском языке (как делали, например, авторы перевода Zero Escape: Zero Time Dilemma, см. например https://github.com/miegir/AI2Tools/blob/30e4512352737d5232ebaaaa9b6cf315344c27d9/AI2Tools.Translations/ru/Text/en/file_info_ID.txt#L325). Т.е. я стараюсь, чтобы перевод выглядел настолько профессиональным, насколько возможно, по крайней мере значительно лучше, чем многие машинные переводы, **и не содержал ошибок вообще**. Вместе с этим я не являюсь профессиональным переводчиком и не настолько хорошо знаю английский, как некоторые, поэтому все же перевод мой можно считать любительским. На подготовку этого перевода ушло четыре месяца по паре и больше часов в день, это можно видеть в истории репозитория. И я считаю, что мой перевод ближе к ручному, чем к машинному.

Кстати, русские шрифты я искал, выбирал и редактировал вручную, здесь никакой машинный переводчик ни при чем. Также картинки (текстуры) и видео я редактировал вручную, и машинный переводчик здесь также ни при чем.

В переводе бонуса "Каюта 3-го класса", отсылающего к Nonary Games, я по максимуму использовал фразы из имеющегося русификатора, чтобы еще больше поддержать дух этой отсылки.

С vndb и их правилами я не знаком, перевод этот делал "для себя", это для меня просто хобби.

Я допускаю, что вполне где-то можно перевести лучше и наверняка где-то есть неточности, особенно в переводах этих странных песен, но исходники перевода потому и лежат в гитхабе, чтобы кто-то при необходимости мог его улучшить.

**Comment by miegir** [comment]
Кстати, перевод двух изображений я не осилил:
- https://github.com/miegir/AI2Tools/blob/master/AI2Tools.Translations/ru/aa/ui-ai_sight_assets_all/Assets/Asset/graphics/2d/Image/ai_sight/c440_M1_00.png
- https://github.com/miegir/AI2Tools/blob/master/AI2Tools.Translations/ru/aa/ui-ai_sight_assets_all/Assets/Asset/graphics/2d/Image/ai_sight/c440_M1_01.png

Т.к. там довольно сложный фон, чтобы за разумное время убрать на нем исходные надписи. Но перевод их текстом в любом случае есть. Может быть, кто-то когда-то их перерисует (может быть даже при помощи ИИ). С другой стороны, эти изображения можно рассматривать как надписи операционной системы, поэтому наверное допускается им быть и без перевода.

В остальных случаях на изображениях находятся те же фразы, что и в тексте.

**Comment by derelictsoul** [comment]
Все понятно, большое спасибо за пояснения. Удачи в следующих переводах, если они будут.
